### ISSUE TITLE
[geostyler-style] Add support for multiple symbolizers

### ISSUE THREAD

**Issue by chrismayer** [terrestris/geostyler#248] opened 2018-06-25 11:43 UTC
Currently a `Rule` can have exactly one Symbolizer. This should be enhanced so a Rule can have one or more symbolizers.

**Comment by KaiVolland** [comment] 2018-06-25 11:51
Somewhat duplicate of https://github.com/terrestris/geostyler/issues/85 but it targets the Style here.

**Comment by chrismayer** [comment] 2018-06-25 11:59
> Somewhat duplicate of #85 but it targets the Style here.

Right...I change the title of #85 so it becomes clearer that is is related to the SLD-Parser (whereas this is related to geostyler-style).

**Comment by KaiVolland** [comment] 2018-10-25 06:46
Solved with #332

**Closed by KaiVolland** 2018-10-25 06:46 UTC
