### ISSUE TITLE
i18n: Buttons to switch language are not translated 

### ISSUE THREAD

**Issue by chrismayer** [terrestris/geostyler#425] opened 2018-09-17 07:28 UTC
The buttons to change the language of the GeoStyler GUI are not translated. They remain English even German is activated as GUI language:

![image](https://user-images.githubusercontent.com/1185547/45610328-dbf72e80-ba5b-11e8-9bb9-7b9b0420c246.png)

Is this by intention or is this a bug?

**Comment by jansule** [comment] 2018-10-01 14:49
It is not a bug. The buttons were added to the demo outside of the locale wrapper, because in my understanding they are not part of the geostyler library. Should this be changed? Otherwise, a quickfix would be to rename the buttons to `DE` and `EN` respectively.

**Comment by jansule** [comment] 2018-11-20 09:45
Since the externalisation of the geostyler-demo application, the buttons look like this:

![image](https://user-images.githubusercontent.com/12186477/48764888-38bbd300-ecb1-11e8-95fa-a42f229b5ab6.png)

This should be fine, I guess. -> Closing this issue

**Closed by jansule** 2018-11-20 09:45 UTC
Labels: question
